* #100DaysOfCode Log - Round 1 - [Mr. Cai]
:PROPERTIES:
:CUSTOM_ID: daysofcode-log---round-1---mr.-cai
:END:
The log of my #100DaysOfCode challenge. Started on [May 13, Friday,
2022]. 100 天编程调整记录。从 22 年五月 13 号开始。

** 计划
:PROPERTIES:
:CUSTOM_ID: 计划
:END:
- 学习 V 语言
- 学习使用 neovim
- 配置 Emacs
- 写一个 cad 简单图形程序

** Log 记录
:PROPERTIES:
:CUSTOM_ID: log-记录
:END:
*** R1D1 第一天
:PROPERTIES:
:CUSTOM_ID: r1d1-第一天
:END:
**** 给 Emacs 建立写 md 文档的设置
:PROPERTIES:
:CUSTOM_ID: 给-emacs-建立写-md-文档的设置
:END:
- 办公室环境是 wsl+arch

org 文件比较熟悉，现在准备改写 md 了，要学习一些新的东西。
还有要给选择是写 org 文件，把 md 改成 org。 先看看 md 怎么样吧。

- 结果是不太想学习 Emacs 了，准备拥抱 vim 怀抱了

- 在 arch 系统里 安装了 ssh 生成了 GitHub 的密钥，发到了 GitHub
  网站，这样这个系统就可以 push 了。

**** 继续学习 neovim
:PROPERTIES:
:CUSTOM_ID: 继续学习-neovim
:END:
nvchad: https://nvchad.github.io/getting-started/setup - 熟悉 lua 语法
https://www.bilibili.com/video/BV1QL4y147VD?p=3 - 学习快捷键的设定
应该是 nvim 的第三课，nvim from scratch 系列教程。 keymap

*** R1D2 第二天
:PROPERTIES:
:CUSTOM_ID: r1d2-第二天
:END:
- 在拉取的时候 git
  给出提示需要设定拉取的默认规则，在本地仓库里给出设定为
  rebase=false，意思是直接合并。
- 继续学习 nvim 入门教程

时间：+1h

- 继续学习 nvim：第四天的课程，是讲解插件的管理，使用的是 packer。
- 拖延症的四种表现。有一项就是准备工作。正如我在做的东西，也可以算作是一种拖延吧。

*** R1D3 第三天
:PROPERTIES:
:CUSTOM_ID: r1d3-第三天
:END:
- 继续学习配置 nvim：今天是主题颜色，视频时长 16 分钟，
- 看了一会儿，mac M1 芯片的电脑虚拟化的教程，推荐使用 UTM
  安装了软件，试了下 arch 不成功。
- 浏览 HN， 看了第三、四、五代编程语言。
- 一个网站，给初学者教授全栈的个人网站，https://thefullstackdev.net/
- 一个个人网站，只使用 html 来写， https://bjhess.com/
  可以学一下，很简单的
- 昨天看了一篇文章，一个大牛的写的关于 web 网页的糟点，认为应该重新考虑
  web
  的发展，从头来做。https://macwright.com/2020/08/22/clean-starts-for-the-web.html，这个网站，
  看了作者是一个很厉害的人物。

*** R1D4 第四天
:PROPERTIES:
:CUSTOM_ID: r1d4-第四天
:END:
- nvim 自动完成设置。
- 安装 org 插件 发现了问题： 无法安装 orgmode.nvim 的插件。报错是没有 cc
  clang 等的编译器。 开始安装 gcc12.1 居然没有 gcc 的安装我晕了。 安装了
  base-devel
- 终于搞好了，原来是需要编译的。
- 在 vnim 里编辑了一下日志文件，是 org 格式的，发现有些功能是没有的，没有 Emacs 完善。估计还是要留在这里 Emacs 了。
- 发现了两个有趣的项目，记录在 roam 了。
  [file:~/Learn/github/my-notes/journal.org][5yue16ri]]

*** R1D5 第五天

#+begin_src shell

# convert md to org-mode
pandoc r1-log.md -s -o r1-log.org
# 还是在Emacs里编辑org习惯！
#+end_src
#+begin_src emacs-lisp
;; 插入设计戳，提示出现 对话框 输入时间。
(org-time-stamp) ;; SPA m d t

#+end_src

*** R1D6 第六天
学点什么呢，v语言似乎有点不流行？
vlang
都差不多吧。
要的话晚上来看看。
♨️一天，Gaming......
*** R1D7 第七天
<2022-05-20 Fri 19:00>
工作比较忙，学习时间少了不少。
还是找书，浏览书籍。没怎么深入看书。
又浏览了一些书，记了一些笔记，在 roam 里面。
**** vlang 继续吧 学习一下 gui 编程
**** 编程环境建立
Emacs doom 加上 v-mode
https://github.com/damon-kwok/v-mode
#+begin_src emacs-lisp
(use-package v-mode
  :straight (v-mode
             :type git
             :host github
             :repo "damon-kwok/v-mode"
             :files ("tokens" "v-mode.el"))
  :config
  :bind-keymap
  ("M-z" . v-menu)
  ("<f6>" . v-menu)
  ("C-c C-f" . v-format-buffer)
  :mode ("\\(\\.v?v\\|\\.vsh\\)$" . 'v-mode))

#+end_src

上面的代码这是报错，最后通过 M-x package-install 来安装的，加了设置。
还可以。
成功了。
#+begin_src v
fn main() {
println('hello world!!!')
            }

#+end_src
#+begin_src shell
v run hello

#+end_src
*** R1D8 第八天
<2022-05-22 Sun 15:00>
**** 新的想法，建立一个文件来追踪一个学习时间记录
感觉建立一个 execel 文件比较好是吧，因为简单一些。好统计。
计划要学习 keynote 和 number 了。
**** 目前的尝试是 使用苹果日历，来安排活动，增加了 学习和非学习两个日历，
分别设置不同的颜色。
*** R1D9 第九天
    思考学习什么编程技术。
    整理一下学到的东西，最近刚学习了c语言，想起了学习C项目：nvim项目。可以作为新手项目来学习一下。
    <2022-05-23 Mon 16:18> 
    似乎自己的水平还不够哇！！
**** 以前学过的东西整理：
     - C
     - JS  HTML  CSS elm react vue svelte hugo lisp racket scheme emacs ruby rails python 
       ios
       swift OC java linux unix 
       克服拖延症，时间管理，


     发现5月21号没有学习，忘记了忘记自己为什么没有写日记了。我晕死了。
     
